export const sampleData = [
  {
    projectName: "Hospital refurbishment",
    dateAdded: "10/01/2022",
    siteAddress: "Unit 35/87 Toolga StMount Column QLD 4573",
    role: "Head Contractor",
    compliance: "Ok",
    units: "40",
    pta: "Yes",
    rta: "Yes",
  },
  {
    projectName: "Train Station Development Toowoomba",
    dateAdded: "10/01/2022",
    siteAddress: "Unit 35/87 Toolga StMount Column QLD 4573",
    role: "Client",
    compliance: "Action Required",
    units: "3",
    pta: "No",
    rta: "No",
  },
  {
    projectName: "Bank/Trust Account Id",
    dateAdded: "10/01/2022",
    siteAddress: "Unit 35/87 Toolga StMount Column QLD 4573",
    role: "Sub Sub-Contractor",
    compliance: "Action Required",
    units: "0",
    pta: "Yes",
    rta: "Yes",
  },
];
