export enum Role {
    PORTAL_ADMIN = 'PORTAL ADMIN',
    RESTRICTED_PORTAL_ADMIN = 'RESTRICTED PORTAL ADMIN',
    PRIMARY_ADMIN = 'PRIMARY ADMIN',
    ADMIN = 'ADMIN',
    STANDARD_USER = 'STANDARD USER',
    BASIC_USER = 'BASIC USER'
}