import "bootstrap/dist/css/bootstrap.css";
import type { Metadata } from "next";
import Layout from "@/components/SideBar";
import Navbar from "@/components/header/navbar";
import styles from "./CompanyDashboarsLayout.module.scss";
import UserDashBoardNavBar from "@/components/header/userDashboard/userDashboardNavbar";


export const metadata: Metadata = {
  title: "Pay Trade",
  description: "Generated by create next app",
};

export default function DashBoardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={styles.containerWraper}>
      <Navbar navlinkClass={""}>
        <UserDashBoardNavBar />
      </Navbar>
      <div className={styles.bodyContainer}>
        <div className={styles.mainConatianer}>
          <div className={styles.sidebarContainer}>
            <Layout isMainBar />
          </div>
          <div className={styles.contentDataCon}>
            <div className={styles.sliderSlideBar}>
              <Layout isMainBar={false} />
            </div>

            {children}
          </div>
        </div>
      </div>
    </div>
  );
}
