const typeOfCompliances = {
  pta: {
    CHECK_CONTRACT_ELIGIBILITY: "CHECK CONTRACT ELIGIBILITY",
    OPEN_PROJECT_TRUST_ACCOUNT: "OPEN PROJECT TRUST ACCOUNT",
    NOTIFY_PARTIES_OF_THE_TRUST_ACCOUNT: "NOTIFY PARTIES OF THE TRUST ACCOUNT",
    ADMINISTRATION_OF_THE_ACCOUNT: "ADMINISTRATION OF THE ACCOUNT",
    PAYMENTS_FROM_THE_PRINCIPAL: "PAYMENTS FROM THE PRINCIPAL",
    PAYMENTS_TO_SUBCONTRACTORS: "PAYMENTS TO SUBCONTRACTORS",
    PAYMENTS_TO_YOURSELF_AS_TRUSTEE: "PAYMENTS TO YOURSELF AS TRUSTEE",
    MONTHLY_RECONCILIATIONS_AND_RECORD_KEEPING:
      "MONTHLY RECONCILIATIONS AND RECORDKEEPING",
    ANNUAL_ACCOUNT_REVIEW_REPORTS: "ANNUAL ACCOUNT REVIEW REPORTS",
    CLOSE_THE_ACCOUNT: "CLOSE THE ACCOUNT",
  },
  rta: {
    RELEASING_RETENTION_AMOUNTS_TO_CONTRACTED_PARTIES:
      "RELEASING RETENTION AMOUNTS TO CONTRACTED PARTIES",
    ADMINISTRATION_OF_THE_ACCOUNT: "ADMINISTRATION OF THE ACCOUNT",
    WITHHOLDING_RETENTION_AMOUNTS_FROM_PAYMENT:
      "WITHHOLDING RETENTION AMOUNTS FROM PAYMENT",
    MONTHLY_RECONCILIATIONS_AND_RECORD_KEEPING:
      "MONTHLY RECONCILIATIONS AND RECORDKEEPING",
    RELEASING_RETENTION_AMOUNTS_TO_YOURSELF_AS_TRUSTEE:
      "RELEASING RETENTION AMOUNTS TO YOURSELF AS TRUSTEE",
    NOTIFY_PARTIES_OF_THE_TRUST_ACCOUNT: "NOTIFY PARTIES OF THE TRUST ACCOUNT",
    OPEN_RETENTION_TRUST_ACCOUNT: "OPEN RETENTION TRUST ACCOUNT",
    RELEASING_RETENTION_AMOUNTS_TO_SOMEONE_ELSE_FROM_THE_ACCOUNT:
      "RELEASING RETENTION AMOUNTS TO SOMEONE ELSE FROM THE ACCOUNT",
    CHECK_CONTRACT_ELIGIBILITY: "CHECK CONTRACT ELIGIBILITY",
    CLOSE_THE_ACCOUNT: "CLOSE THE ACCOUNT",
    ANNUAL_ACCOUNT_REVIEW_REPORTS: "ANNUAL ACCOUNT REVIEW REPORTS",
  },
};

export { typeOfCompliances };
