export const sampleData = [
  {
    dateCreated: "20/02/2023",
    projectName: "Project 1 name",
    contractName: "Contract name xyz",
    buyerName: "Principal company name",
    sellerName: "Carma UK Construction Limited",
    contractSum: "$ 12,000,567.00",
    agreedVariations: "$",
    id: 100,
  },
  {
    dateCreated: "21/02/2023",
    projectName: "Project x name",
    contractName: "Contract name xyz",
    buyerName: "Carma UK Construction Limited",
    sellerName: "XYZ Company STP Profile",
    contractSum: "$2,000,000.00",
    agreedVariations: "",
    id: 200,
  },
  {
    dateCreated: "22/02/2023",
    projectName: "Project 44 name",
    contractName: "Contract name xyz",
    buyerName: "Carma UK Construction Limited",
    sellerName: "XYZ Company STP Profile",
    contractSum: "$2,000,000.00",
    agreedVariations: "",
    id: 300,
  },
  {
    dateCreated: "23/02/2023",
    projectName: "Project 5000 name",
    contractName: "Contract name xyz",
    buyerName: "Carma UK Construction Limited",
    sellerName: "XYZ Company STP Profile",
    contractSum: "$2,000,000.00",
    agreedVariations: "",
    id: 400,
  },
  {
    dateCreated: "24/02/2023",
    projectName: "Another project name 3",
    contractName: "Contract name xyz",
    buyerName: "Carma UK Construction Limited",
    sellerName: "XYZ Company STP Profile",
    contractSum: "$2,000,000.00",
    agreedVariations: "",
    id: 500,
  },
  {
    dateCreated: "25/02/2023",
    projectName: "My biggest project name 4",
    contractName: "Contract name xyz",
    buyerName: "Carma UK Construction Limited",
    sellerName: "XYZ Company STP Profile",
    contractSum: "$2,000,000.00",
    agreedVariations: "",
    id: 600,
  },
  {
    dateCreated: "26/02/2023",
    projectName: "Another cool project 1",
    contractName: "Contract name xyz",
    buyerName: "Carma UK Construction Limited",
    sellerName: "XYZ Company STP Profile",
    contractSum: "$1,000,000.00",
    agreedVariations: "$ 20,000.00",
    id: 700,
  },
  {
    dateCreated: "27/02/2023",
    projectName: "Horrid project",
    contractName: "Contract name xyz",
    buyerName: "Carma UK Construction Limited",
    sellerName: "XYZ Company STP Profile",
    contractSum: "$ 7,000.00",
    agreedVariations: "$ 5,000.00",
    id: 800,
  },
];
