const Roles = {
  SUPER_ADMIN_ROLE: "PORTAL ADMIN",
  RESTRICTED_ADMIN: "RESTRICTED PORTAL ADMIN",
  ADMIN_ROLE: "ADMIN",
  USER_ROLE_BASIC: "BASIC USER",
  USER_ROLE_STANDARD: "STANDARD USER",
  USER_PRIMARY_ADMIN: "PRIMARY ADMIN",
};

const UserRoles = [
  Roles.USER_ROLE_BASIC,
  Roles.USER_ROLE_STANDARD,
  Roles.USER_PRIMARY_ADMIN,
  Roles.ADMIN_ROLE,
];

const AdminRoles = [Roles.SUPER_ADMIN_ROLE, Roles.RESTRICTED_ADMIN];

export { UserRoles, AdminRoles, Roles };
