import seoMetadata from "./seoMetadata";

export const JSON_LD = {
  default: {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: seoMetadata.default.title,
    url: seoMetadata.default.alternates?.canonical,
    description: seoMetadata.default.description,
    operatingSystem: "Web",
    applicationCategory: "AccountingApplication",
    author: {
      "@type": "Organization",
      name: "Carma 360 Pty Ltd",
    },
    publisher: {
      "@type": "Organization",
      name: "Carma 360 Pty Ltd",
    },
    featureList: [
      "Account opening & onboarding",
      "Process payment applications",
      "Record and match payments",
      "Reconcile and audit",
      "Ongoing compliance review",
      "Free onboarding support",
      "Ongoing eligibility checks",
      "Integrations with accounting/project management software",
      "Australian-based support centre",
      "Online community and knowledge base",
    ],
    offers: {
      "@type": "Offer",
      price: "0.00",
      priceCurrency: "AUD",
      description:
        "Free trial available with full access to trust compliance tools for principals and clients.",
    },
    supportingData: {
      "@type": "WebSite",
      name: "PayTrade",
      url: process.env.NEXT_PUBLIC_DEPLOYED_URL,
    },
    inLanguage: "en-AU",
    offersSupport: {
      "@type": "ContactPoint",
      contactType: "customer support",
      availableLanguage: "en-AU",
      areaServed: "AU",
    },
  },
  principals: {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: seoMetadata.principals.title,
    url: seoMetadata.principals.alternates?.canonical,
    description: seoMetadata.principals.description,
    inLanguage: "en-AU",
    about: {
      "@type": "SoftwareApplication",
      name: "PayTrade",
      applicationCategory: "AccountingApplication",
      operatingSystem: "Web",
      offers: {
        "@type": "Offer",
        price: "0.00",
        priceCurrency: "AUD",
        description:
          "Free trial available with full access to trust compliance tools for principals and clients.",
      },
      featureList: [
        "Fast setup and onboarding",
        "Unlimited users and multiple businesses",
        "Professional collaboration with accountants and auditors",
        "Automated eligibility checks",
        "Trust account opening with compliance validation",
        "Claim processing with import options",
        "Automated payment matching and ABA file export",
        "Regulatory notice submission to QBCC",
        "Bank feed connections and reconciliations",
        "Automated retention processing and record creation",
        "Full reporting and audit preparation",
        "Dashboard for monitoring trust compliance",
        "App integrations",
        "Delegated trust processing authority",
        "Supplier management features",
      ],
    },
    publisher: {
      "@type": "Organization",
      name: "Carma 360 Pty Ltd",
    },
    mainEntity: {
      "@type": "FAQPage",
      name: "Trust Compliance Features for Principals & Clients",
      mainEntity: [
        {
          "@type": "Question",
          name: "Can I manage multiple businesses with PayTrade?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, PayTrade allows management of multiple businesses, projects, and trust accounts from a single login.",
          },
        },
        {
          "@type": "Question",
          name: "Does PayTrade help submit QBCC notices?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, you can submit QBCC notices automatically through the platform.",
          },
        },
        {
          "@type": "Question",
          name: "Can I delegate trust processing to PayTrade?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, PayTrade can handle notice submissions and trust account processing on your behalf.",
          },
        },
      ],
    },
  },
  bookkeepers: {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: seoMetadata.bookkeepers.title,
    url: seoMetadata.bookkeepers.alternates?.canonical,
    description: seoMetadata.bookkeepers.description,
    inLanguage: "en-AU",
    about: {
      "@type": "SoftwareApplication",
      name: "PayTrade",
      applicationCategory: "AccountingApplication",
      operatingSystem: "Web",
      offers: {
        "@type": "Offer",
        price: "0.00",
        priceCurrency: "AUD",
        description:
          "Free trial available for bookkeepers managing trust compliance for multiple clients.",
      },
      featureList: [
        "Fast setup and onboarding for bookkeepers",
        "Unlimited user access across multiple businesses",
        "Share access with clients and professionals",
        "Eligibility checks and monitoring",
        "Open and manage trust and general accounts",
        "Billable claims import and management",
        "Match and schedule payments",
        "Submit QBCC notices and alerts",
        "Link bank feeds for automation",
        "Process and track retentions",
        "Create trust account records",
        "Monthly reconciliation and audit support",
        "Integration with other bookkeeping software",
        "Automated QBCC and client reporting",
        "Delegate notice submission to PayTrade",
        "View head contractor and project data",
        "Dashboard for monitoring compliance and activity",
      ],
    },
    publisher: {
      "@type": "Organization",
      name: "Carma 360 Pty Ltd",
    },
    mainEntity: {
      "@type": "FAQPage",
      name: "Bookkeepers and Trust Compliance",
      mainEntity: [
        {
          "@type": "Question",
          name: "How can PayTrade help bookkeepers with trust compliance?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "PayTrade helps bookkeepers manage trust account compliance, automate reporting, and integrate with their existing accounting tools.",
          },
        },
        {
          "@type": "Question",
          name: "Can bookkeepers manage multiple businesses and clients?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, PayTrade supports unlimited users and allows bookkeepers to manage multiple businesses, projects, and trust accounts from one platform.",
          },
        },
        {
          "@type": "Question",
          name: "Does PayTrade automate reconciliations and reporting?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, PayTrade automates monthly reconciliations, QBCC compliance reporting, and submission of regulatory notices.",
          },
        },
      ],
    },
  },
  headContractors: {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: seoMetadata.headContractors.title,
    url: seoMetadata.headContractors.alternates?.canonical,
    description: seoMetadata.headContractors.description,
    inLanguage: "en-AU",
    about: {
      "@type": "SoftwareApplication",
      name: "PayTrade",
      applicationCategory: "AccountingApplication",
      operatingSystem: "Web",
      offers: {
        "@type": "Offer",
        price: "0.00",
        priceCurrency: "AUD",
        description:
          "Free trial available for head contractors managing project and retention trust accounts.",
      },
      featureList: [
        "Fast setup for trust account compliance",
        "Support for multiple projects, businesses, and users",
        "Eligibility checks with contract monitoring",
        "Trust and general account onboarding",
        "Claim processing with import functionality",
        "Automated payments and ABA export",
        "Automatic notice submission to QBCC",
        "Linked bank feeds and reconciliations",
        "Retention list and account management",
        "Monthly reconciliation and audit assistance",
        "Software integrations",
        "Automated compliance monitoring and alerts",
        "Dashboard to track compliance and accounts",
      ],
    },
    publisher: {
      "@type": "Organization",
      name: "Carma 360 Pty Ltd",
    },
    mainEntity: {
      "@type": "FAQPage",
      name: "PayTrade for Head Contractors FAQs",
      mainEntity: [
        {
          "@type": "Question",
          name: "What does PayTrade offer for head contractors?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "PayTrade helps head contractors manage project and retention trust accounts, automate QBCC compliance, submit notices, and reconcile trust transactions efficiently.",
          },
        },
        {
          "@type": "Question",
          name: "Can I use PayTrade to manage multiple projects and businesses?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, PayTrade supports unlimited users and the management of multiple businesses, projects, and contacts from a single account.",
          },
        },
        {
          "@type": "Question",
          name: "Does PayTrade support bank feed connections and ABA exports?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, PayTrade connects with your bank for real-time feeds and provides ABA file exports to automate your payment processes.",
          },
        },
      ],
    },
  },
  auditors: {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: seoMetadata.auditors.title,
    url: seoMetadata.auditors.alternates?.canonical,
    description: seoMetadata.auditors.description,
    inLanguage: "en-AU",
    about: {
      "@type": "SoftwareApplication",
      name: "PayTrade",
      applicationCategory: "AccountingApplication",
      operatingSystem: "Web",
      offers: {
        "@type": "Offer",
        price: "0.00",
        priceCurrency: "AUD",
        description:
          "Free trial available for auditors assisting with QBCC audit documentation and compliance.",
      },
      featureList: [
        "Fast integration for compliance audits",
        "Support for multiple clients and trust accounts",
        "Eligibility checks with automated monitoring",
        "Streamlined onboarding for trust and general accounts",
        "Claim and payment recording tools",
        "Automated ABA file generation for payments",
        "Notice submissions to QBCC",
        "Bank feed connections and reconciliation automation",
        "Retention management tools",
        "Trust account records generation",
        "Monthly reconciliation and audit support",
        "Integration with other business software",
        "Automated compliance review and alerts",
        "Client access delegation for accountants and legal support",
        "Real-time compliance dashboard",
      ],
    },
    publisher: {
      "@type": "Organization",
      name: "Carma 360 Pty Ltd",
    },
    mainEntity: {
      "@type": "FAQPage",
      name: "PayTrade for Auditors FAQs",
      mainEntity: [
        {
          "@type": "Question",
          name: "How does PayTrade help auditors?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "PayTrade allows auditors to collect and submit audit documentation for trust accounts and supports ongoing QBCC compliance for their clients in the construction industry.",
          },
        },
        {
          "@type": "Question",
          name: "Can auditors access multiple clients through PayTrade?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, auditors can manage and review multiple businesses and trust accounts within a single platform using PayTrade.",
          },
        },
        {
          "@type": "Question",
          name: "Does PayTrade offer automated reconciliation features?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, PayTrade connects to bank feeds and automates reconciliations to simplify monthly audit processes for auditors.",
          },
        },
      ],
    },
  },
  subcontractors: {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: seoMetadata.subcontractors.title,
    url: seoMetadata.subcontractors.alternates?.canonical,
    description: seoMetadata.subcontractors.description,
    inLanguage: "en-AU",
    about: {
      "@type": "SoftwareApplication",
      name: "PayTrade",
      applicationCategory: "AccountingApplication",
      operatingSystem: "Web",
      offers: {
        "@type": "Offer",
        price: "0.00",
        priceCurrency: "AUD",
        description:
          "Free trial available for subcontractors managing QBCC-compliant trust accounts.",
      },
      featureList: [
        "Fast set-up for immediate compliance",
        "Manage multiple trust accounts and businesses",
        "Automated eligibility checks",
        "Onboarding for trust and general accounts",
        "Claims processing with import functionality",
        "Automated payment matching and ABA file generation",
        "Notices submission to QBCC and contractors",
        "Auto compliance monitoring and alerts",
        "Linked bank feeds for reconciliations",
        "Retention and trust account record management",
        "Monthly reconciliation and audit support",
        "Software integrations",
        "Comprehensive reporting automation",
        "Role-based access for support professionals",
        "Real-time dashboard for compliance and operations",
      ],
    },
    publisher: {
      "@type": "Organization",
      name: "Carma 360 Pty Ltd",
    },
    mainEntity: {
      "@type": "FAQPage",
      name: "PayTrade for Subcontractors FAQs",
      mainEntity: [
        {
          "@type": "Question",
          name: "How does PayTrade help subcontractors stay compliant?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "PayTrade automates trust account compliance, notice submissions, and QBCC reporting, helping subcontractors easily meet legal obligations in the Australian construction industry.",
          },
        },
        {
          "@type": "Question",
          name: "Can subcontractors manage multiple trust accounts?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, PayTrade enables subcontractors to manage multiple projects, businesses, and trust accounts from a single platform.",
          },
        },
        {
          "@type": "Question",
          name: "Does PayTrade integrate with other accounting tools?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, PayTrade integrates with commonly used business and accounting software to streamline trust account workflows.",
          },
        },
      ],
    },
  },
  legalPractitioners: {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: seoMetadata.legalPractitioners.title,
    url: seoMetadata.legalPractitioners.alternates?.canonical,
    description: seoMetadata.legalPractitioners.description,
    inLanguage: "en-AU",
    about: {
      "@type": "SoftwareApplication",
      name: "PayTrade",
      applicationCategory: "AccountingApplication",
      operatingSystem: "Web",
      offers: {
        "@type": "Offer",
        price: "0.00",
        priceCurrency: "AUD",
        description:
          "Free trial available for legal practitioners to manage trust accounts and compliance.",
      },
      featureList: [
        "Fast integration for immediate compliance",
        "Manage multiple businesses, trusts, and projects",
        "Eligibility checks and ongoing monitoring",
        "Trust and general account onboarding",
        "Processing billable claims with head contractors",
        "Automated payment matching and ABA file exports",
        "Notices submission to QBCC and contractors",
        "Auto compliance monitoring and alerts",
        "Bank feed integration for reconciliations",
        "Retention management and trust accounting automation",
        "Automatic creation of retention trust account records",
        "Monthly reconciliation and audit documentation",
        "App integrations with other software providers",
        "Automated reporting to QBCC and contractors",
        "Delegated authority for trust accounting processing",
        "Manage contractor and supplier details in one place",
        "Comprehensive dashboard for real-time compliance tracking",
      ],
    },
    publisher: {
      "@type": "Organization",
      name: "Carma 360 Pty Ltd",
    },
    mainEntity: {
      "@type": "FAQPage",
      name: "PayTrade for Legal Practitioners FAQs",
      mainEntity: [
        {
          "@type": "Question",
          name: "How does PayTrade help legal practitioners?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "PayTrade simplifies the compliance and trust account management process for legal practitioners, ensuring that their clients stay compliant with QBCC and evolving construction laws.",
          },
        },
        {
          "@type": "Question",
          name: "Can legal practitioners manage multiple businesses with PayTrade?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, legal practitioners can manage multiple businesses, projects, trusts, and contracts all from a single PayTrade account.",
          },
        },
        {
          "@type": "Question",
          name: "Does PayTrade automate compliance monitoring for legal practitioners?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, PayTrade includes an automatic compliance monitoring system to help legal practitioners ensure their clients are always in compliance with QBCC regulations.",
          },
        },
      ],
    },
  },
  accountants: {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: seoMetadata.accountants.title,
    url: seoMetadata.accountants.alternates?.canonical,
    description: seoMetadata.accountants.description,
    inLanguage: "en-AU",
    about: {
      "@type": "SoftwareApplication",
      name: "PayTrade",
      applicationCategory: "AccountingApplication",
      operatingSystem: "Web",
      offers: {
        "@type": "Offer",
        price: "0.00",
        priceCurrency: "AUD",
        description:
          "Free trial available for accountants to manage trust accounts and compliance.",
      },
      featureList: [
        "Fast integration for immediate compliance",
        "Manage multiple businesses, trusts, and projects",
        "Eligibility checks and ongoing monitoring",
        "Trust and general account onboarding",
        "Processing billable claims with head contractors",
        "Automated payment matching and ABA file exports",
        "Notices submission to QBCC and contractors",
        "Auto compliance monitoring and alerts",
        "Bank feed integration for reconciliations",
        "Retention management and trust accounting automation",
        "Automatic creation of retention trust account records",
        "Monthly reconciliation and audit documentation",
        "App integrations with other software providers",
        "Automated reporting to QBCC and contractors",
        "Delegated authority for trust accounting processing",
        "Manage contractor and supplier details in one place",
        "Comprehensive dashboard for real-time compliance tracking",
      ],
    },
    publisher: {
      "@type": "Organization",
      name: "Carma 360 Pty Ltd",
    },
    mainEntity: {
      "@type": "FAQPage",
      name: "PayTrade for Accountants FAQs",
      mainEntity: [
        {
          "@type": "Question",
          name: "How does PayTrade help accountants?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "PayTrade helps accountants automate trust account management, ensuring compliance with QBCC regulations and reducing manual processes for their clients.",
          },
        },
        {
          "@type": "Question",
          name: "Can accountants manage multiple businesses with PayTrade?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, accountants can manage multiple businesses, projects, trusts, and contracts from a single PayTrade account.",
          },
        },
        {
          "@type": "Question",
          name: "Does PayTrade automate compliance monitoring for accountants?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, PayTrade includes an automatic compliance monitoring system that helps accountants ensure their clients stay compliant with all regulatory requirements.",
          },
        },
      ],
    },
  },
  features: {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: seoMetadata.features.title,
    url: seoMetadata.features.alternates?.canonical,
    description: seoMetadata.features.description,
    inLanguage: "en-AU",
    about: {
      "@type": "SoftwareApplication",
      name: "PayTrade",
      applicationCategory: "AccountingApplication",
      operatingSystem: "Web",
      featureList: [
        "Fast set-up and easy integration",
        "Manage unlimited users, businesses, projects, and trusts",
        "Initial and ongoing eligibility checks",
        "Trust and general account onboarding",
        "Process and import billable claims",
        "Match payments and schedules with ABA file exports",
        "Automatic QBCC notice submission",
        "Compliance monitoring and alerts",
        "Bank feed integration and reconciliation automation",
        "Retention management and trust account recording",
        "Monthly reconciliations and audit support",
        "Integration with external apps",
        "Automated QBCC and head contractor reporting",
        "Delegate authority for notice submission",
        "Manage head contractor details",
        "Comprehensive dashboard for monitoring all activities",
      ],
    },
    publisher: {
      "@type": "Organization",
      name: "Carma 360 Pty Ltd",
    },
  },
  getSupport: {
    "@context": "https://schema.org",
    "@type": "ContactPage",
    name: seoMetadata.getSupport.title,
    url: seoMetadata.getSupport.alternates?.canonical,
    description: seoMetadata.getSupport.description,
    mainEntity: {
      "@type": "Organization",
      name: "Carma 360 Pty Ltd",
      contactPoint: {
        "@type": "ContactPoint",
        contactType: "Customer Support",
        email: "support@paytrade.com.au",
        availableLanguage: ["en-AU"],
        areaServed: "AU",
      },
    },
  },
};
