export const contractAccountType = [
  {
    client_supplier_type: 'Client',
    project_role: 'Head Contractor',
    client_supplier_role: 'Principal',
    related_entity: ['Yes', 'No'],
    pta_eligibility: 'Yes',
    payment_to_account: ['Cash Account', 'Project Trust Account'],
  },
  {
    client_supplier_type: 'Client',
    project_role: 'Head Contractor',
    client_supplier_role: 'Principal',
    related_entity: ['Yes', 'No'],
    pta_eligibility: 'No',
    payment_to_account: ['Cash Account'],
  },
  {
    client_supplier_type: 'Client',
    project_role: 'Sub Contractor',
    client_supplier_role: 'Head Contractor',
    related_entity: ['Yes'],
    pta_eligibility: 'Yes',
    payment_to_account: ['Cash Account', 'Project Trust Account'],
  },
  {
    client_supplier_type: 'Client',
    project_role: 'Sub Contractor',
    client_supplier_role: 'Head Contractor',
    related_entity: ['No'],
    pta_eligibility: 'Yes',
    payment_to_account: ['Cash Account'],
  },
  {
    client_supplier_type: 'Client',
    project_role: 'Sub Contractor',
    client_supplier_role: 'Head Contractor',
    related_entity: ['Yes', 'No'],
    pta_eligibility: 'No',
    payment_to_account: ['Cash Account'],
  },
  {
    client_supplier_type: 'Supplier',
    project_role: 'Principal',
    client_supplier_role: 'Head Contractor',
    related_entity: ['Yes', 'No'],
    pta_eligibility: 'Yes',
    payment_from_account: ['Cash Account'],
    payment_to_account: ['Cash Account', 'Project Trust Account'],
  },
  {
    client_supplier_type: 'Supplier',
    project_role: 'Principal',
    client_supplier_role: 'Head Contractor',
    related_entity: ['Yes', 'No'],
    pta_eligibility: 'No',
    payment_from_account: ['Cash Account'],
    payment_to_account: ['Cash Account'],
  },
  {
    client_supplier_type: 'Supplier',
    project_role: 'Head Contractor',
    client_supplier_role: 'Related Entity Sub Contractor',
    related_entity: ['Yes'],
    pta_eligibility: 'Yes',
    payment_from_account: ['Project Trust Account'],
    payment_to_account: ['Cash Account', 'Project Trust Account'],
  },
  {
    client_supplier_type: 'Supplier',
    project_role: 'Head Contractor',
    client_supplier_role: 'Sub Contractor',
    related_entity: ['No'],
    pta_eligibility: 'Yes',
    payment_from_account: ['Project Trust Account'],
    payment_to_account: ['Cash Account'],
  },
  {
    client_supplier_type: 'Supplier',
    project_role: 'Head Contractor',
    client_supplier_role: 'Related Entity Sub Contractor',
    related_entity: ['Yes'],
    pta_eligibility: 'No',
    payment_from_account: ['Cash Account'],
    payment_to_account: ['Cash Account'],
  },
  {
    client_supplier_type: 'Supplier',
    project_role: 'Head Contractor',
    client_supplier_role: 'Sub Contractor',
    related_entity: ['No'],
    pta_eligibility: 'No',
    payment_from_account: ['Cash Account'],
    payment_to_account: ['Cash Account'],
  },
  {
    client_supplier_type: 'Supplier',
    project_role: 'Sub Contractor',
    client_supplier_role: 'Sub Contractor',
    related_entity: ['Yes', 'No'],
    pta_eligibility: 'Yes',
    payment_from_account: ['Cash Account'],
    payment_to_account: ['Cash Account'],
  },
  {
    client_supplier_type: 'Supplier',
    project_role: 'Sub Contractor',
    client_supplier_role: 'Sub Contractor',
    related_entity: ['Yes', 'No'],
    pta_eligibility: 'No',
    payment_from_account: ['Cash Account'],
    payment_to_account: ['Cash Account'],
  },
  {
    client_supplier_type: 'Supplier',
    project_role: 'Sub Contractor',
    client_supplier_role: 'Related Entity Sub Contractor',
    related_entity: ['Yes', 'No'],
    pta_eligibility: 'Yes',
    payment_from_account: ['Cash Account'],
    payment_to_account: ['Cash Account'],
  },
  {
    client_supplier_type: 'Supplier',
    project_role: 'Sub Contractor',
    client_supplier_role: 'Related Entity Sub Contractor',
    related_entity: ['Yes', 'No'],
    pta_eligibility: 'No',
    payment_from_account: ['Cash Account'],
    payment_to_account: ['Cash Account'],
  },
];
