export const paymentStatusArray = [
  {
    claim_status_in_db: 'Draft',
    claim_status_in_ui: 'Please complete the claim form and mark as completed',
    claim_type: ['Billable', 'Receivable'],
    cash_retention_type: ['Payment', 'Retention'],
  },
  {
    claim_status_in_db: 'Confirmed',
    claim_status_in_ui: 'Claim confirmed. Please add Payment',
    claim_type: ['Billable', 'Receivable'],
    cash_retention_type: ['Payment', 'Retention'],
  },
  {
    claim_status_in_db: 'Deleted',
    claim_status_in_ui: 'Archive - Deleted',
    claim_type: ['Billable', 'Receivable'],
    cash_retention_type: ['Payment', 'Retention'],
  },
  {
    claim_status_in_db: 'Paid - Matched',
    claim_status_in_ui: 'Payment due to 3rd party via new payment claim',
    claim_type: ['Billable'],
    payment_type: '3rd Party',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Payment due to 3rd party via new payment claim',
    cash_retention_type: ['Payment', 'Retention'],
  },
  {
    claim_status_in_db: 'Paid - Matched',
    claim_status_in_ui: 'Payment due to 3rd party',
    claim_type: ['Receivable'],
    payment_type: '3rd Party',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Payment due to 3rd party',
    cash_retention_type: ['Payment', 'Retention'],
  },
  {
    claim_status_in_db: 'Paid - Matched',
    claim_status_in_ui: 'No payment due',
    claim_type: ['Billable'],
    payment_type: 'Pay - Zero',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'No payment due',
  },
  {
    claim_status_in_db: 'Received - Matched',
    claim_status_in_ui: 'No payment due',
    claim_type: ['Receivable'],
    payment_type: 'Pay - Zero',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'No payment due',
  },
  {
    claim_status_in_db: 'Not Paid - Unmatched',
    claim_status_in_ui:
      'Full payment paid - Please match transaction in account',
    claim_type: ['Billable'],
    payment_type: 'Full',
    payment_status_in_db: 'Unmatched',
    retention_status_in_db: 'Unmatched',
    payment_status_in_ui:
      'Full payment paid - Please match transaction in account',
    cash_retention_type: ['Payment'],
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    claim_status_in_db: 'Paid - Unmatched',
    claim_status_in_ui:
      'Full payment paid - Please match transaction in account',
    claim_type: ['Billable'],
    payment_type: 'Full',
    payment_status_in_db: 'Unmatched',
    retention_status_in_db: 'Unmatched',
    payment_status_in_ui:
      'Full payment paid - Please match transaction in account',
    cash_retention_type: ['Payment'],
    is_paid_confirmed: true,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    claim_status_in_db: 'Paid - Matched',
    claim_status_in_ui: 'Full payment paid and matched',
    claim_type: ['Billable'],
    payment_type: 'Full',
    payment_status_in_db: 'Matched',
    retention_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Full payment paid and matched',
    cash_retention_type: ['Payment'],
    is_paid_confirmed: false, //line 80
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    claim_status_in_db:
      'NotPaid PymntMatched RetentionOutUnmatched RetentionInUnmatched',
    claim_status_in_ui:
      'Full payment due - Please match the retained payment out of the Payment from account and into the Retention account.',
    claim_type: ['Billable'],
    payment_type: 'Full',
    payment_status_in_db: 'Matched',
    retention_status_in_db: 'Unmatched',
    payment_status_in_ui:
      'Full payment due - Please match the retained payment out of the Payment from account and into the Retention account.',
    cash_retention_type: ['Retention'],
    is_paid_confirmed: false,
    is_retention_confirmed: false,
    is_received_confirmed: false,
  },
  {
    claim_status_in_db:
      'NotPaid PymntUnmatched RetentionOutMatched RetentionInUnmatched',
    claim_status_in_ui:
      'Full payment due - Please confirm and match the payment claim payment to the supplier and the retained payment into the retention account',
    claim_type: ['Billable'],
    payment_type: 'Full',
    payment_status_in_db: 'Unmatched',
    retention_status_in_db: 'Unmatched',
    payment_status_in_ui:
      'Full payment due - Please confirm and match the payment claim payment to the supplier and the retained payment into the retention account',
    cash_retention_type: ['Retention'],
    is_paid_confirmed: false,
    is_retention_confirmed: true,
    is_received_confirmed: false,
  },
  {
    claim_status_in_db:
      'NotPaid PymntUnmatched RetentionOutUnmatched RetentionInMatched',
    claim_status_in_ui:
      'Full payment due - Please confirm and match the payment claim payment to the supplier and the retained payment out of the payment from account',
    claim_type: ['Billable'],
    payment_type: 'Full',
    payment_status_in_db: 'Unmatched',
    retention_status_in_db: 'Matched',
    payment_status_in_ui:
      'Full payment due - Please confirm and match the payment claim payment to the supplier and the retained payment out of the payment from account',
    cash_retention_type: ['Retention'],
    is_paid_confirmed: false,
    is_retention_confirmed: false,
    is_received_confirmed: false,
  },
  {
    claim_status_in_db:
      'NotPaid PymntMatched RetentionOutMatched RetentionInUnmatched',
    claim_status_in_ui:
      'Full payment due - Please confirm and match the retention payment into the retention account',
    claim_type: ['Billable'],
    payment_type: 'Full',
    payment_status_in_db: 'Matched',
    retention_status_in_db: 'Unmatched',
    payment_status_in_ui:
      'Full payment due - Please confirm and match the retention payment into the retention account',
    cash_retention_type: ['Retention'],
    is_paid_confirmed: false,
    is_retention_confirmed: true,
    is_received_confirmed: false,
  },
  {
    claim_status_in_db:
      'NotPaid PymntMatched RetentionOutUnmatched RetentionInMatched',
    claim_status_in_ui:
      'Full payment due - Please confirm and match the retained payment out of the payment from account',
    claim_type: ['Billable'],
    payment_type: 'Full',
    payment_status_in_db: 'Matched',
    retention_status_in_db: 'Matched',
    payment_status_in_ui:
      'Full payment due - Please confirm and match the retained payment out of the payment from account',
    cash_retention_type: ['Retention'],
    is_paid_confirmed: false,
    is_retention_confirmed: false,
    is_received_confirmed: false,
  },
  {
    claim_status_in_db:
      'Paid PymntMatched RetentionOutUnmatched RetentionInUnmatched',
    claim_status_in_ui:
      'Full payment due - Please match the retained payment out of the Payment from account and into the Retention account.',
    claim_type: ['Billable'],
    payment_type: 'Full',
    payment_status_in_db: 'Matched',
    retention_status_in_db: 'Unmatched',
    payment_status_in_ui:
      'Full payment due - Please match the retained payment out of the Payment from account and into the Retention account.',
    cash_retention_type: ['Retention'],
    is_paid_confirmed: true,
    is_retention_confirmed: false,
    is_received_confirmed: false,
  },
  {
    // need to check line 98
    claim_status_in_db: 'Not Paid - Unmatched',
    claim_status_in_ui:
      'Please match the retained payment out of the Payment from account and into the Retention account.',
    claim_type: ['Billable'],
    payment_type: 'Full',
    payment_status_in_db: 'Unmatched',
    retention_status_in_db: 'Unmatched',
    payment_status_in_ui:
      'Please match the retained payment out of the Payment from account and into the Retention account.',
    cash_retention_type: ['Retention'],
    is_paid_confirmed: false,
    is_retention_confirmed: false,
    is_received_confirmed: false,
  },
  {
    claim_status_in_db:
      'NotPaid PymntUnmatched RetentionOutMatched RetentionInMatched',
    claim_status_in_ui:
      'Full payment due - Please confirm and match the payment claim payment to the supplier',
    claim_type: ['Billable'],
    payment_type: 'Full',
    payment_status_in_db: 'Unmatched',
    retention_status_in_db: 'Matched',
    payment_status_in_ui:
      'Full payment due - Please confirm and match the payment claim payment to the supplier',
    cash_retention_type: ['Retention'],
    is_paid_confirmed: false,
    is_retention_confirmed: true,
    is_received_confirmed: false,
  },
  {
    claim_status_in_db:
      'Paid PymntUnmatched RetentionOutMatched RetentionInUnmatched',
    claim_status_in_ui:
      'Please match the payment claim payment to the supplier and the retention payment into the retention account',
    claim_type: ['Billable'],
    payment_type: 'Full',
    payment_status_in_db: 'Unmatched',
    retention_status_in_db: 'Unmatched',
    payment_status_in_ui:
      'Please match the payment claim payment to the supplier and the retention payment into the retention account',
    cash_retention_type: ['Retention'],
    is_paid_confirmed: true,
    is_retention_confirmed: true,
    is_received_confirmed: false,
  },
  {
    claim_status_in_db:
      'Paid PymntUnmatched RetentionOutMatched RetentionInMatched',
    claim_status_in_ui:
      'Please match the payment claim payment to the supplier',
    claim_type: ['Billable'],
    payment_type: 'Full',
    payment_status_in_db: 'Unmatched',
    retention_status_in_db: 'Matched',
    payment_status_in_ui:
      'Please match the payment claim payment to the supplier',
    cash_retention_type: ['Retention'],
    is_paid_confirmed: true,
    is_retention_confirmed: true,
    is_received_confirmed: false,
  },
  {
    claim_status_in_db:
      'Paid PymntUnmatched RetentionOutUnmatched RetentionInMatched',
    claim_status_in_ui:
      'Please match the retained payment out of the Payment from account and into the Retention account.',
    claim_type: ['Billable'],
    payment_type: 'Full',
    payment_status_in_db: 'Unmatched',
    retention_status_in_db: 'Matched',
    payment_status_in_ui:
      'Please match the retained payment out of the Payment from account and into the Retention account.',
    cash_retention_type: ['Retention'],
    is_paid_confirmed: true,
    is_retention_confirmed: false,
    is_received_confirmed: false,
  },
  {
    claim_status_in_db:
      'Paid PymntMatched RetentionOutUnmatched RetentionInMatched',
    claim_status_in_ui:
      'Please match the retained payment out of the Payment from account',
    claim_type: ['Billable'],
    payment_type: 'Full',
    payment_status_in_db: 'Matched',
    retention_status_in_db: 'Matched',
    payment_status_in_ui:
      'Please match the retained payment out of the Payment from account',
    cash_retention_type: ['Retention'],
    is_paid_confirmed: true,
    is_retention_confirmed: false,
    is_received_confirmed: false,
  },
  {
    claim_status_in_db:
      'Paid PymntMatched RetentionOutMatched RetentionInUnmatched',
    claim_status_in_ui:
      'Please match the retention payment into the retention account',
    claim_type: ['Billable'],
    payment_type: 'Full',
    payment_status_in_db: 'Matched',
    retention_status_in_db: 'Unmatched',
    payment_status_in_ui:
      'Please match the retention payment into the retention account',
    cash_retention_type: ['Retention'],
    is_paid_confirmed: true,
    is_retention_confirmed: true,
    is_received_confirmed: false,
  },
  {
    claim_status_in_db: 'Received - Unmatched',
    claim_status_in_ui:
      'Full payment received - Please match transaction in account',
    claim_type: ['Receivable'],
    payment_type: 'Full',
    payment_status_in_db: 'Unmatched',
    retention_status_in_db: 'Unmatched',
    payment_status_in_ui:
      'Full payment received - Please match transaction in account',
    cash_retention_type: ['Payment', 'Retention'],
    is_received_confirmed: true,
    is_paid_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    claim_status_in_db: 'Received - Matched',
    claim_status_in_ui: 'Full payment received and matched',
    claim_type: ['Receivable'],
    payment_type: 'Full',
    payment_status_in_db: 'Matched',
    retention_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Full payment received and matched',
    cash_retention_type: ['Payment', 'Retention'],
    is_received_confirmed: false,
    is_paid_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    claim_status_in_db: 'Received - Matched',
    claim_status_in_ui: 'Full payment received and matched',
    claim_type: ['Receivable'],
    payment_type: 'Full',
    payment_status_in_db: 'Matched',
    retention_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Full payment received and matched',
    cash_retention_type: ['Payment', 'Retention'],
    is_received_confirmed: true,
    is_paid_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Interest Received',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui:
      'Interest Receivable due - Please match transaction in account',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Interest Received',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui:
      'Interest Received - Please match transaction in account',
    is_paid_confirmed: false,
    is_received_confirmed: true,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Interest Received',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Interest Receivable due and matched',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Interest Received',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Interest Received and matched',
    is_paid_confirmed: false,
    is_received_confirmed: true,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Interest Withdrawal',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui:
      'Interest Withdrawal due - Please match transaction in account',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Interest Withdrawal',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui:
      'Interest Withdrawal Paid - Please match transaction in account',
    is_paid_confirmed: true,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Interest Withdrawal',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Interest Withdrawal due and matched',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Interest Withdrawal',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Interest Withdrawal Paid and matched',
    is_paid_confirmed: true,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Bank Charge Applied',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Not Paid - Please match transaction in account',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Bank Charge Applied',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Paid - Please match transaction in account',
    is_paid_confirmed: true,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Bank Charge Applied',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Not Paid and matched',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Bank Charge Applied',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Paid and matched',
    is_paid_confirmed: true,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Bank Charge Top Up',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Not Received - Please match transaction in account',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Bank Charge Top Up',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Received - Please match transaction in account',
    is_paid_confirmed: false,
    is_received_confirmed: true,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Bank Charge Top Up',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Not Received and matched',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Bank Charge Top Up',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Received and matched',
    is_paid_confirmed: false,
    is_received_confirmed: true,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Top Up',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Not Received - Please match transaction in account',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Top Up',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Received - Please match transaction in account',
    is_paid_confirmed: false,
    is_received_confirmed: true,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Top Up',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Not Received and matched',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Top Up',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Received and matched',
    is_paid_confirmed: false,
    is_received_confirmed: true,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Withdrawal',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Not Paid - Please match transaction in account',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Withdrawal',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Paid - Please match transaction in account',
    is_paid_confirmed: true,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Withdrawal',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Not Paid and matched',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Withdrawal',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Paid and matched',
    is_paid_confirmed: true,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Top Up Retention',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Not Received - Please match transaction in account',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Top Up Retention',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Received - Please match transaction in account',
    is_paid_confirmed: false,
    is_received_confirmed: true,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Top Up Retention',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Not Received and matched',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Top Up Retention',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Received and matched',
    is_paid_confirmed: false,
    is_received_confirmed: true,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Overpayment refund to client',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Not Paid - Please match transaction in account',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Overpayment refund to client',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Paid - Please match transaction in account',
    is_paid_confirmed: true,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Overpayment refund to client',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Not Paid and matched',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Overpayment refund to client',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Paid and matched',
    is_paid_confirmed: true,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Overpayment refund from supplier',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Not Received - Please match transaction in account',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Overpayment refund from supplier',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Received - Please match transaction in account',
    is_paid_confirmed: false,
    is_received_confirmed: true,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Overpayment refund from supplier',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Not Received and matched',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Overpayment refund from supplier',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Received and matched',
    is_paid_confirmed: false,
    is_received_confirmed: true,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Overpayment to supplier',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Please confirm and match the overpayment',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Overpayment to supplier',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Please match the overpayment',
    is_paid_confirmed: true,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Overpayment to supplier',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Overpayment matched',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Overpayment to supplier',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Overpayment matched',
    is_paid_confirmed: true,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Underpayment to supplier',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Please confirm and match the underpayment',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Underpayment to supplier',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Please match the underpayment',
    is_paid_confirmed: true,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Underpayment to supplier',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Underpayment matched',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Underpayment to supplier',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Underpayment matched',
    is_paid_confirmed: true,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Overpayment from client',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Please confirm and match the overpayment',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Overpayment from client',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Please match the overpayment',
    is_paid_confirmed: true,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Overpayment from client',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Overpayment matched',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Overpayment from client',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Overpayment matched',
    is_paid_confirmed: true,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Underpayment from client',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Please confirm and match the underpayment',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Underpayment from client',
    payment_status_in_db: 'Unmatched',
    payment_status_in_ui: 'Please match the underpayment',
    is_paid_confirmed: true,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Underpayment from client',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Underpayment matched',
    is_paid_confirmed: false,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
  {
    payment_type: 'Underpayment from client',
    payment_status_in_db: 'Matched',
    payment_status_in_ui: 'Underpayment matched',
    is_paid_confirmed: true,
    is_received_confirmed: false,
    is_retention_confirmed: false,
  },
];
