export const paymentStatus = [
  {
    claim_type: ['Billable', 'Receivable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Pay - Zero', '3rd Party'],
    claim_status: 'No Match Required',
    payment_status: 'No Match Required',
    list_status: 'Completed',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Unconfirmed - Unmatched',
    payment_status: 'Unconfirmed - Unmatched',
    cash_retention: false,
    is_paid_confirmed: false,
    payment_matched: false,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Unconfirmed - Unmatched',
    payment_status: 'Unconfirmed - Unmatched',
    cash_retention: true,
    is_paid_confirmed: false,
    is_retention_confirmed: false,
    payment_matched: false,
    retention_out_matched: false,
    retention_in_matched: false,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Unconfirmed - Unmatched',
    payment_status: 'Unconfirmed - Unmatched',
    cash_retention: true,
    is_paid_confirmed: false,
    is_retention_confirmed: true,
    payment_matched: false,
    retention_out_matched: false,
    retention_in_matched: false,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Unconfirmed - Unmatched',
    payment_status: 'Unconfirmed - Unmatched',
    cash_retention: true,
    is_paid_confirmed: true,
    is_retention_confirmed: false,
    payment_matched: false,
    retention_out_matched: false,
    retention_in_matched: false,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Unconfirmed - Payment Unmatched - Retention Out Matched - Retention In Unmatched',
    payment_status:
      'Unconfirmed - Payment Unmatched - Retention Out Matched - Retention In Unmatched',
    cash_retention: true,
    is_paid_confirmed: false,
    is_retention_confirmed: false,
    payment_matched: false,
    retention_out_matched: true,
    retention_in_matched: false,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Unconfirmed - Payment Unmatched - Retention Out Matched - Retention In Unmatched',
    payment_status:
      'Unconfirmed - Payment Unmatched - Retention Out Matched - Retention In Unmatched',
    cash_retention: true,
    is_paid_confirmed: false,
    is_retention_confirmed: true,
    payment_matched: false,
    retention_out_matched: true,
    retention_in_matched: false,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Unconfirmed - Payment Unmatched - Retention Out Matched - Retention In Unmatched',
    payment_status:
      'Unconfirmed - Payment Unmatched - Retention Out Matched - Retention In Unmatched',
    cash_retention: true,
    is_paid_confirmed: true,
    is_retention_confirmed: false,
    payment_matched: false,
    retention_out_matched: true,
    retention_in_matched: false,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Unconfirmed - Payment Unmatched - Retention Out Unmatched - Retention In Matched',
    payment_status:
      'Unconfirmed - Payment Unmatched - Retention Out Unmatched - Retention In Matched',
    cash_retention: true,
    is_paid_confirmed: false,
    is_retention_confirmed: false,
    payment_matched: false,
    retention_out_matched: false,
    retention_in_matched: true,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Unconfirmed - Payment Unmatched - Retention Out Unmatched - Retention In Matched',
    payment_status:
      'Unconfirmed - Payment Unmatched - Retention Out Unmatched - Retention In Matched',
    cash_retention: true,
    is_paid_confirmed: false,
    is_retention_confirmed: true,
    payment_matched: false,
    retention_out_matched: false,
    retention_in_matched: true,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Unconfirmed - Payment Unmatched - Retention Out Unmatched - Retention In Matched',
    payment_status:
      'Unconfirmed - Payment Unmatched - Retention Out Unmatched - Retention In Matched',
    cash_retention: true,
    is_paid_confirmed: true,
    is_retention_confirmed: false,
    payment_matched: false,
    retention_out_matched: false,
    retention_in_matched: true,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Unconfirmed - Payment Unmatched - Retention Out Matched - Retention In Matched',
    payment_status:
      'Unconfirmed - Payment Unmatched - Retention Out Matched - Retention In Matched',
    cash_retention: true,
    is_paid_confirmed: false,
    is_retention_confirmed: false,
    payment_matched: false,
    retention_out_matched: true,
    retention_in_matched: true,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Unconfirmed - Payment Unmatched - Retention Out Matched - Retention In Matched',
    payment_status:
      'Unconfirmed - Payment Unmatched - Retention Out Matched - Retention In Matched',
    cash_retention: true,
    is_paid_confirmed: false,
    is_retention_confirmed: true,
    payment_matched: false,
    retention_out_matched: true,
    retention_in_matched: true,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Unconfirmed - Payment Unmatched - Retention Out Matched - Retention In Matched',
    payment_status:
      'Unconfirmed - Payment Unmatched - Retention Out Matched - Retention In Matched',
    cash_retention: true,
    is_paid_confirmed: true,
    is_retention_confirmed: false,
    payment_matched: false,
    retention_out_matched: true,
    retention_in_matched: true,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Unconfirmed - Payment Matched - Retention Out Unmatched - Retention In Unmatched',
    payment_status:
      'Unconfirmed - Payment Matched - Retention Out Unmatched - Retention In Unmatched',
    cash_retention: true,
    is_paid_confirmed: false,
    is_retention_confirmed: false,
    payment_matched: true,
    retention_out_matched: false,
    retention_in_matched: false,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Unconfirmed - Payment Matched - Retention Out Unmatched - Retention In Unmatched',
    payment_status:
      'Unconfirmed - Payment Matched - Retention Out Unmatched - Retention In Unmatched',
    cash_retention: true,
    is_paid_confirmed: false,
    is_retention_confirmed: true,
    payment_matched: true,
    retention_out_matched: false,
    retention_in_matched: false,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Unconfirmed - Payment Matched - Retention Out Unmatched - Retention In Unmatched',
    payment_status:
      'Unconfirmed - Payment Matched - Retention Out Unmatched - Retention In Unmatched',
    cash_retention: true,
    is_paid_confirmed: true,
    is_retention_confirmed: false,
    payment_matched: true,
    retention_out_matched: false,
    retention_in_matched: false,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Unconfirmed - Payment Matched - Retention Out Matched - Retention In Unmatched',
    payment_status:
      'Unconfirmed - Payment Matched - Retention Out Matched - Retention In Unmatched',
    cash_retention: true,
    is_paid_confirmed: false,
    is_retention_confirmed: false,
    payment_matched: true,
    retention_out_matched: true,
    retention_in_matched: false,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Unconfirmed - Payment Matched - Retention Out Matched - Retention In Unmatched',
    payment_status:
      'Unconfirmed - Payment Matched - Retention Out Matched - Retention In Unmatched',
    cash_retention: true,
    is_paid_confirmed: false,
    is_retention_confirmed: true,
    payment_matched: true,
    retention_out_matched: true,
    retention_in_matched: false,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Unconfirmed - Payment Matched - Retention Out Matched - Retention In Unmatched',
    payment_status:
      'Unconfirmed - Payment Matched - Retention Out Matched - Retention In Unmatched',
    cash_retention: true,
    is_paid_confirmed: true,
    is_retention_confirmed: false,
    payment_matched: true,
    retention_out_matched: true,
    retention_in_matched: false,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Unconfirmed - Payment Matched - Retention Out Unmatched - Retention In Matched',
    payment_status:
      'Unconfirmed - Payment Matched - Retention Out Unmatched - Retention In Matched',
    cash_retention: true,
    is_paid_confirmed: false,
    is_retention_confirmed: false,
    payment_matched: true,
    retention_out_matched: false,
    retention_in_matched: true,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Unconfirmed - Payment Matched - Retention Out Unmatched - Retention In Matched',
    payment_status:
      'Unconfirmed - Payment Matched - Retention Out Unmatched - Retention In Matched',
    cash_retention: true,
    is_paid_confirmed: false,
    is_retention_confirmed: true,
    payment_matched: true,
    retention_out_matched: false,
    retention_in_matched: true,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Unconfirmed - Payment Matched - Retention Out Unmatched - Retention In Matched',
    payment_status:
      'Unconfirmed - Payment Matched - Retention Out Unmatched - Retention In Matched',
    cash_retention: true,
    is_paid_confirmed: true,
    is_retention_confirmed: false,
    payment_matched: true,
    retention_out_matched: false,
    retention_in_matched: true,
    list_status: 'Confirm payment',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Paid - Payment Unmatched - Retention Out Matched - Retention In Unmatched',
    payment_status:
      'Paid - Payment Unmatched - Retention Out Matched - Retention In Unmatched',
    cash_retention: true,
    is_paid_confirmed: true,
    is_retention_confirmed: true,
    payment_matched: false,
    retention_out_matched: true,
    retention_in_matched: false,
    list_status: 'Reconcile',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Paid - Payment Unmatched - Retention Out Matched - Retention In Matched',
    payment_status:
      'Paid - Payment Unmatched - Retention Out Matched - Retention In Matched',
    cash_retention: true,
    is_paid_confirmed: true,
    is_retention_confirmed: true,
    payment_matched: false,
    retention_out_matched: true,
    retention_in_matched: true,
    list_status: 'Reconcile',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Paid - Payment Unmatched - Retention Out Unmatched - Retention In Matched',
    payment_status:
      'Paid - Payment Unmatched - Retention Out Unmatched - Retention In Matched',
    cash_retention: true,
    is_paid_confirmed: true,
    is_retention_confirmed: true,
    payment_matched: false,
    retention_out_matched: false,
    retention_in_matched: true,
    list_status: 'Reconcile',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Paid - Payment Matched - Retention Out Unmatched - Retention In Matched',
    payment_status:
      'Paid - Payment Matched - Retention Out Unmatched - Retention In Matched',
    cash_retention: true,
    is_paid_confirmed: true,
    is_retention_confirmed: true,
    payment_matched: true,
    retention_out_matched: false,
    retention_in_matched: true,
    list_status: 'Reconcile',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Paid - Payment Matched - Retention Out Matched - Retention In Unmatched',
    payment_status:
      'Paid - Payment Matched - Retention Out Matched - Retention In Unmatched',
    cash_retention: true,
    is_paid_confirmed: true,
    is_retention_confirmed: true,
    payment_matched: true,
    retention_out_matched: true,
    retention_in_matched: false,
    list_status: 'Reconcile',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status:
      'Paid - Payment Matched - Retention Out Unmatched - Retention In Unmatched',
    payment_status:
      'Paid - Payment Matched - Retention Out Unmatched - Retention In Unmatched',
    cash_retention: true,
    is_paid_confirmed: true,
    is_retention_confirmed: true,
    payment_matched: true,
    retention_out_matched: false,
    retention_in_matched: false,
    list_status: 'Reconcile',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Paid - Unmatched',
    payment_status: 'Paid - Unmatched',
    cash_retention: false,
    is_paid_confirmed: true,
    payment_matched: false,
    list_status: 'Reconcile',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Paid - Unmatched',
    payment_status: 'Paid - Unmatched',
    cash_retention: true,
    is_paid_confirmed: true,
    is_retention_confirmed: true,
    payment_matched: false,
    retention_out_matched: false,
    retention_in_matched: false,
    list_status: 'Reconcile',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Paid - Matched',
    payment_status: 'Paid - Matched',
    cash_retention: false,
    is_paid_confirmed: true,
    payment_matched: true,
    list_status: 'Completed',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Paid - Matched',
    payment_status: 'Paid - Matched',
    cash_retention: true,
    is_paid_confirmed: true,
    is_retention_confirmed: true,
    payment_matched: true,
    retention_out_matched: true,
    retention_in_matched: true,
    list_status: 'Completed',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Unconfirmed - Matched',
    payment_status: 'Unconfirmed - Matched',
    cash_retention: false,
    is_paid_confirmed: false,
    payment_matched: true,
    list_status: 'Completed',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Unconfirmed - Matched',
    payment_status: 'Unconfirmed - Matched',
    cash_retention: true,
    is_paid_confirmed: false,
    is_retention_confirmed: true,
    payment_matched: true,
    retention_out_matched: true,
    retention_in_matched: true,
    list_status: 'Completed',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Unconfirmed - Matched',
    payment_status: 'Unconfirmed - Matched',
    cash_retention: true,
    is_paid_confirmed: true,
    is_retention_confirmed: false,
    payment_matched: true,
    retention_out_matched: true,
    retention_in_matched: true,
    list_status: 'Completed',
  },
  {
    claim_type: ['Billable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Unconfirmed - Matched',
    payment_status: 'Unconfirmed - Matched',
    cash_retention: true,
    is_paid_confirmed: false,
    is_retention_confirmed: false,
    payment_matched: true,
    retention_out_matched: true,
    retention_in_matched: true,
    list_status: 'Completed',
  },
  {
    claim_type: ['Receivable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Unconfirmed - Unmatched',
    payment_status: 'Unconfirmed - Unmatched',
    cash_retention: false,
    is_received_confirmed: false,
    payment_matched: false,
    list_status: 'Confirm receipt',
  },
  {
    claim_type: ['Receivable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Unconfirmed - Unmatched',
    payment_status: 'Unconfirmed - Unmatched',
    cash_retention: true,
    is_received_confirmed: false,
    payment_matched: false,
    list_status: 'Confirm receipt',
  },
  {
    claim_type: ['Receivable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Received - Unmatched',
    payment_status: 'Received - Unmatched',
    cash_retention: false,
    is_received_confirmed: true,
    payment_matched: false,
    list_status: 'Reconcile',
  },
  {
    claim_type: ['Receivable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Received - Unmatched',
    payment_status: 'Received - Unmatched',
    cash_retention: true,
    is_received_confirmed: true,
    payment_matched: false,
    list_status: 'Reconcile',
  },
  {
    claim_type: ['Receivable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Received - Matched',
    payment_status: 'Received - Matched',
    cash_retention: false,
    is_received_confirmed: true,
    payment_matched: true,
    list_status: 'Completed',
  },
  {
    claim_type: ['Receivable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Received - Matched',
    payment_status: 'Received - Matched',
    cash_retention: true,
    is_received_confirmed: true,
    payment_matched: true,
    list_status: 'Completed',
  },
  {
    claim_type: ['Receivable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Unconfirmed - Matched',
    payment_status: 'Unconfirmed - Matched',
    cash_retention: false,
    is_received_confirmed: false,
    payment_matched: true,
    list_status: 'Completed',
  },
  {
    claim_type: ['Receivable'],
    cash_retention_type: ['Claim', 'Retention claim'],
    payment_type: ['Full', 'Part', 'Pay Less - Full', 'Pay Less - Part'],
    claim_status: 'Unconfirmed - Matched',
    payment_status: 'Unconfirmed - Matched',
    cash_retention: true,
    is_received_confirmed: false,
    payment_matched: true,
    list_status: 'Completed',
  },
  {
    payment_type: [
      'Interest Withdrawal',
      'Bank Charge Applied',
      'Withdrawal',
      'Overpayment refund to client',
      'Overpayment to supplier',
      'Underpayment to supplier',
    ],
    claim_status: 'Unconfirmed - Unmatched',
    payment_status: 'Unconfirmed - Unmatched',
    is_paid_confirmed: false,
    payment_matched: false,
    list_status: 'Confirm payment',
  },
  {
    payment_type: [
      'Interest Withdrawal',
      'Bank Charge Applied',
      'Withdrawal',
      'Overpayment refund to client',
      'Overpayment to supplier',
      'Underpayment to supplier',
    ],
    claim_status: 'Paid - Unmatched',
    payment_status: 'Paid - Unmatched',
    is_paid_confirmed: true,
    payment_matched: false,
    list_status: 'Reconcile',
  },
  {
    payment_type: [
      'Interest Received',
      'Bank Charge Top Up',
      'Top Up',
      'Top Up Retention',
      'Overpayment refund from supplier',
      'Overpayment from client',
      'Underpayment from client',
    ],
    claim_status: 'Unconfirmed - Unmatched',
    payment_status: 'Unconfirmed - Unmatched',
    is_received_confirmed: false,
    payment_matched: false,
    list_status: 'Confirm receipt',
  },
  {
    payment_type: [
      'Interest Received',
      'Bank Charge Top Up',
      'Top Up',
      'Top Up Retention',
      'Overpayment refund from supplier',
      'Overpayment from client',
      'Underpayment from client',
    ],
    claim_status: 'Received - Unmatched',
    payment_status: 'Received - Unmatched',
    is_received_confirmed: true,
    payment_matched: false,
    list_status: 'Reconcile',
  },
  ///matched other payments
  {
    payment_type: [
      'Interest Withdrawal',
      'Bank Charge Applied',
      'Withdrawal',
      'Overpayment refund to client',
      'Overpayment to supplier',
      'Underpayment to supplier',
    ],
    claim_status: 'Unconfirmed - Matched',
    payment_status: 'Unconfirmed - Matched',
    is_paid_confirmed: false,
    payment_matched: true,
    list_status: 'Completed',
  },
  {
    payment_type: [
      'Interest Withdrawal',
      'Bank Charge Applied',
      'Withdrawal',
      'Overpayment refund to client',
      'Overpayment to supplier',
      'Underpayment to supplier',
    ],
    claim_status: 'Paid - Matched',
    payment_status: 'Paid - Matched',
    is_paid_confirmed: true,
    payment_matched: true,
    list_status: 'Completed',
  },
  {
    payment_type: [
      'Interest Received',
      'Bank Charge Top Up',
      'Top Up',
      'Top Up Retention',
      'Overpayment refund from supplier',
      'Overpayment from client',
      'Underpayment from client',
    ],
    claim_status: 'Unconfirmed - Matched',
    payment_status: 'Unconfirmed - Matched',
    is_received_confirmed: false,
    payment_matched: true,
    list_status: 'Completed',
  },
  {
    payment_type: [
      'Interest Received',
      'Bank Charge Top Up',
      'Top Up',
      'Top Up Retention',
      'Overpayment refund from supplier',
      'Overpayment from client',
      'Underpayment from client',
    ],
    claim_status: 'Received - Matched',
    payment_status: 'Received - Matched',
    is_received_confirmed: true,
    payment_matched: true,
    list_status: 'Completed',
  },
];
