const SUPER_ADMIN_ROLE = "PORTAL ADMIN";
const RESTRICTED_ADMIN = "RESTRICTED PORTAL ADMIN";

const ADMIN_ROLE = "ADMIN"; //this is user role only
const USER_ROLE_BASIC = "BASIC USER";
const USER_ROLE_STANDARD = "STANDARD USER";
const USER_PRIMARY_ADMIN = "PRIMARY ADMIN";

const ALL_USER_ROLES = [
  USER_ROLE_BASIC,
  USER_ROLE_STANDARD,
  USER_PRIMARY_ADMIN,
  ADMIN_ROLE,
];

const ALL_ADMIN_ROLES = [SUPER_ADMIN_ROLE, RESTRICTED_ADMIN];

export {
  ALL_USER_ROLES,
  ALL_ADMIN_ROLES,
  USER_ROLE_BASIC,
  USER_ROLE_STANDARD,
  ADMIN_ROLE,
  SUPER_ADMIN_ROLE,
  RESTRICTED_ADMIN,
  USER_PRIMARY_ADMIN,
};
